---
title: "Git & GitHub"
---

# Overview

The point of version control. What *not* to do.

## Git

### Workflow

### Git lingo
        1. Repositories
            1. repository / repo
            1. initialize
            2. clone
            3. branch & checkout
        2. Version control
            1. commit
            3. stage
            4. fetch
            6. pull
            7. push
        3. Merging
            1. diff
            2. merge
            3. merge conflict
            4. rebase
            5. fast-forward (ff)
            6. squash
            7. cherry-pick
            8. stash
        4. Remote repositories
            1. remote
            2. origin
            3. upstream
            4. fork
            5. pull request
        5. (Optional) Using Git in the terminal

## Repo structure

### What does and does not go in a repo?

### Top-level essentials
        1. README
        2. .gitignore

### The rest of your stuff

### Metadata and information

### Example: My go-to repo structure

## GitHub

### What is GitHub? How is it different from Git?

### GitHub features

#### Issues

#### Pull requests

#### Pages

#### Copilot

#### More

We won't use these in this class, but they're worth knowing about.

1. Actions
2. Projects
3. Codespaces
4. Wikis
5. Organizations

### Interfacing with GitHub (without RStudio)

#### GitHub website

#### GitHub Desktop

#### Other options

If you're already comfortable with other tools, you can use them to interface with GitHub. 
We won't use them in this class. Some popular options include:

1. VS Code and other IDEs
2. GitHub CLI

### Interfacing with GitHub in RStudio

#### Connecting RStudio to GitHub

#### Using GitHub in RStudio

The most common git tasks with RStudio:

1. Cloning a repo
2. Committing changes
3. Pushing changes
4. Pulling changes
5. Resolving merge conflicts
6. Creating pull requests

## Git Pains

### Common issues

### Helpful resources

### The nuclear option

# Guided Exercise: Simple GitHub & RStudio sync

Create a repo on GitHub.
Clone it in RStudio.
Make a change in RStudio.
Commit and push the change.
Check the change on GitHub.
Make a change on GitHub (and commit).
Pull the change in RStudio.
Create a conflict by making and committing a change in RStudio and a different (conflicting) change on GitHub.
Resolve the conflict in RStudio.

