---
title: "Solving (Your Own) Problems"
---

# Overview

*Why is this its own chapter?*

# Using AI

## What are we talking about?

Because "AI" means anything these days.

## tl;dr D2M-R AI Policy

Read the rest of this section, but here's the short version (and a link to the policy on 
the course site).

## Ethical vs. Unethical Use

## Constructive vs. Counterproductive Use

## Tips, Tricks, Rules of Thumb

# Best practices

## Standardized

### Style guides

## Intelligible

## Maintainable

## Contextualized

## Example: My style guide and practices

# Debugging & Troubleshooting

## Documentation

### Help/lookup functions

### Function documentation

### Package documentation

### Resources
        
## Solving your own problems

### Error messages

### Garbage in, garbage out (and other tropes)

### Line-by-line debugging

### Rubber ducking
        
## Ask the internet

### Start strong - asking good questions

### Crowdsource

### Use AI constructively
        
## Ask humans (for classrooms and group learning)

### Ask your classmates

### Use Slack

### Ask your instructor & TAs

### The D2M-R troubleshooting process
        
## Starting from "Nothing" 