project:
  type: book

book:
  title: "From Data to Manuscript in R"
  author: "Natalie Dowling"
  date: "6/1/2025"
  chapters:
    - index.qmd
    - Q1/rstudio.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



